version: '3.8'

services:
  maintenance-bot:
    build: .
    container_name: telegram-maintenance-bot
    restart: unless-stopped
    
    # Переменные окружения из .env файла
    env_file:
      - .env
    
    # Монтируем директории для данных
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Настройки безопасности
    security_opt:
      - no-new-privileges:true
    
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "https://api.telegram.org"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
